spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_farming?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: dgvt
    password: dgvt
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 9999
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.it.pojo
  mapper-locations: classpath:mappers/**/*.xml
